name: "Setup Terraform"
description: "Sets up Terraform CLI and configures it"

runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.14.2"
