---
name: infrastructure-destroy
"on":
  workflow_call:
    inputs:
      bucket_name:
        description: "Name of the S3 bucket"
        required: true
        type: string
      tfvar_file_path:
        description: "Path to the tfvar file"
        required: true
        type: string
      approvers:
        description: "List of approvers"
        required: true
        type: string
      master_s3_directory:
        description: "Name of the master s3 directory"
        required: true
        type: string
      component:
        description: "Component to destroy (argocd_configuration, eso_configuration, orchestrator_secret_management, orchestrator_custom_addons, eks_essential_addons, eks_infra, all)"
        required: true
        type: string
      module_ref:
        description: "Branch/tag/ref of orchestrator-plane-setup to use"
        required: false
        type: string
        default: "main"

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  infrastructure-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout orchestrator-plane-setup
        uses: actions/checkout@v4
        with:
          repository: urukube/orchestrator-plane-setup
          path: orchestrator-plane-setup
          ref: ${{ inputs.module_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.OC_ROLE_TO_ASSUME }}
          role-session-name: githubactions-${{ github.run_id }}

      - name: Setup Terraform
        uses: ./orchestrator-plane-setup/.github/actions/terraform-setup

      - name: Set environment variables for Terraform
        run: |
          echo "MASTER_S3_DIRECTORY=${{ inputs.master_s3_directory }}" >> $GITHUB_ENV
          echo "TF_STATE_BUCKET=${{ inputs.bucket_name }}" >> $GITHUB_ENV

      - name: Destroy argocd_configuration
        if: inputs.component == 'argocd_configuration' || inputs.component == 'all'
        uses: ./orchestrator-plane-setup/.github/actions/terraform-plan-destroy
        with:
          bucket_name: ${{ inputs.bucket_name }}
          tfvar_file_path: ${{ inputs.tfvar_file_path }}
          directory: ./orchestrator-plane-setup/argocd-configuration
          approvers: ${{ inputs.approvers }}
          component: argocd_configuration
          master_s3_directory: ${{ inputs.master_s3_directory }}

      - name: Destroy eso_configuration
        if: inputs.component == 'eso_configuration' || inputs.component == 'all'
        uses: ./orchestrator-plane-setup/.github/actions/terraform-plan-destroy
        with:
          bucket_name: ${{ inputs.bucket_name }}
          tfvar_file_path: ${{ inputs.tfvar_file_path }}
          directory: ./orchestrator-plane-setup/eso-configuration
          approvers: ${{ inputs.approvers }}
          component: eso_configuration
          master_s3_directory: ${{ inputs.master_s3_directory }}

      - name: Destroy orchestrator_custom_addons
        if: inputs.component == 'orchestrator_custom_addons' || inputs.component == 'all'
        uses: ./orchestrator-plane-setup/.github/actions/terraform-plan-destroy
        with:
          bucket_name: ${{ inputs.bucket_name }}
          tfvar_file_path: ${{ inputs.tfvar_file_path }}
          directory: ./orchestrator-plane-setup/orchestrator-custom-addons
          approvers: ${{ inputs.approvers }}
          component: orchestrator_custom_addons
          master_s3_directory: ${{ inputs.master_s3_directory }}

      - name: Destroy eks_essential_addons
        if: inputs.component == 'eks_essential_addons' || inputs.component == 'all'
        uses: ./orchestrator-plane-setup/.github/actions/terraform-plan-destroy
        with:
          bucket_name: ${{ inputs.bucket_name }}
          tfvar_file_path: ${{ inputs.tfvar_file_path }}
          directory: ./orchestrator-plane-setup/eks-essential-addons
          approvers: ${{ inputs.approvers }}
          component: eks_essential_addons
          master_s3_directory: ${{ inputs.master_s3_directory }}

      - name: Destroy eks_infra
        if: inputs.component == 'eks_infra' || inputs.component == 'all'
        uses: ./orchestrator-plane-setup/.github/actions/terraform-plan-destroy
        with:
          bucket_name: ${{ inputs.bucket_name }}
          tfvar_file_path: ${{ inputs.tfvar_file_path }}
          directory: ./orchestrator-plane-setup/eks-infra
          approvers: ${{ inputs.approvers }}
          component: eks_infra
          master_s3_directory: ${{ inputs.master_s3_directory }}

      - name: Destroy orchestrator_secret_management
        if: inputs.component == 'orchestrator_secret_management' || inputs.component == 'all'
        uses: ./orchestrator-plane-setup/.github/actions/terraform-plan-destroy
        with:
          bucket_name: ${{ inputs.bucket_name }}
          tfvar_file_path: ${{ inputs.tfvar_file_path }}
          directory: ./orchestrator-plane-setup/orchestrator-secret-management
          approvers: ${{ inputs.approvers }}
          component: orchestrator_secret_management
          master_s3_directory: ${{ inputs.master_s3_directory }}
