---
name: infrastructure-flow
"on":
  workflow_call:
    inputs:
      bucket_name:
        description: "Name of the S3 bucket"
        required: true
        type: string
      tfvar_file_path:
        description: "Path to the tfvar file"
        required: true
        type: string
      approvers:
        description: "List of approvers"
        required: true
        type: string
      master_s3_directory:
        description: "Name of the master s3 directory"
        required: true
        type: string
      module_ref:
        description: "Branch/tag/ref of orchestrator-plane-setup to use"
        required: false
        type: string
        default: "main"

permissions:
  id-token: write
  contents: read
  issues: write
jobs:
  infrastructure-flow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout orchestrator-plane-setup
        uses: actions/checkout@v4
        with:
          repository: urukube/orchestrator-plane-setup
          path: orchestrator-plane-setup
          ref: ${{ inputs.module_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.OC_ROLE_TO_ASSUME }}
          role-session-name: githubactions-${{ github.run_id }}

      - name: Create S3 bucket for Terraform backend
        run: |
          chmod +x ./orchestrator-plane-setup/scripts/create-tf-backend-bucket.sh
          ./orchestrator-plane-setup/scripts/create-tf-backend-bucket.sh ${{ inputs.bucket_name }} us-east-1

      - name: Setup Terraform
        uses: ./orchestrator-plane-setup/.github/actions/terraform-setup

      - name: Set environment variables for Terraform
        run: |
          echo "MASTER_S3_DIRECTORY=${{ inputs.master_s3_directory }}" >> $GITHUB_ENV
          echo "TF_STATE_BUCKET=${{ inputs.bucket_name }}" >> $GITHUB_ENV

      - name: eks_infra
        uses: ./orchestrator-plane-setup/.github/actions/terraform-plan-apply
        with:
          bucket_name: ${{ inputs.bucket_name }}
          tfvar_file_path: ${{ inputs.tfvar_file_path }}
          directory: ./orchestrator-plane-setup/eks-infra
          approvers: ${{ inputs.approvers }}
          component: eks_infra
          master_s3_directory: ${{ inputs.master_s3_directory }}

      - name: eks_essential_addons
        uses: ./orchestrator-plane-setup/.github/actions/terraform-plan-apply
        with:
          bucket_name: ${{ inputs.bucket_name }}
          tfvar_file_path: ${{ inputs.tfvar_file_path }}
          directory: ./orchestrator-plane-setup/eks-essential-addons
          approvers: ${{ inputs.approvers }}
          component: eks_essential_addons
          master_s3_directory: ${{ inputs.master_s3_directory }}

      - name: orchestrator_custom_addons
        uses: ./orchestrator-plane-setup/.github/actions/terraform-plan-apply
        with:
          bucket_name: ${{ inputs.bucket_name }}
          tfvar_file_path: ${{ inputs.tfvar_file_path }}
          directory: ./orchestrator-plane-setup/orchestrator-custom-addons
          approvers: ${{ inputs.approvers }}
          component: orchestrator_custom_addons
          master_s3_directory: ${{ inputs.master_s3_directory }}

      - name: argocd_configuration
        uses: ./orchestrator-plane-setup/.github/actions/terraform-plan-apply
        with:
          bucket_name: ${{ inputs.bucket_name }}
          tfvar_file_path: ${{ inputs.tfvar_file_path }}
          directory: ./orchestrator-plane-setup/argocd-configuration
          approvers: ${{ inputs.approvers }}
          component: argocd_configuration
          master_s3_directory: ${{ inputs.master_s3_directory }}
